name: Android Build Workflow

on:
  push:
    branches:
      - develop  # Triggers on push to develop > staging
      - main     # Triggers on push to main > production

jobs:
  deploy-to-staging:
    if: github.ref == 'refs/heads/develop'  # Only run this job if pushing to develop
    name: Build and Test in Debug Mode
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle (Debug Mode)
        run: ./gradlew assembleDebug
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Run tests
        run: ./gradlew testDebugUnitTest

  deploy-to-production:
    if: github.ref == 'refs/heads/main'  # Only run this job if pushing to main
    name: Build and Deploy Release to Google Play
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode and save keystore file
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > /tmp/keystore.jks

      - name: Build with Gradle (Release Mode)
        run: ./gradlew bundleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          ANDROID_KEYSTORE: /tmp/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Debugging step: Check if AAB file is generated
      - name: List generated files
        run: ls -alh app/build/outputs/bundle/release

      - name: Upload artifact for later use
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Install Fastlane
        run: |
          gem install fastlane --user-install
          export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"

      - name: Upload to Google Play (Internal Testing)
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON" > /tmp/service_account.json
          fastlane supply --aab app/build/outputs/bundle/release/app-release.aab --track internal --json_key /tmp/service_account.json --package_name app.glucostats